name: CD - Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer les fichiers buildés depuis les artefacts
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      # 2. Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
