name: CI - Build & Test on dev

on:
  push:
    branches:
      - dev

jobs:
  build_and_test:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4. Lancer les tests
      - name: Run tests
        run: npm test

      # 5. Builder le projet si tests OK
      - name: Build project
        run: npm run build

      # 6. Uploader les fichiers buildés
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
